### ISSUE TITLE
Updates to requirement 4.3

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/card4l#10]
Another v5.5 update I've noticed are the fields related to 4.3
In the documents the following fields are required as threshold: 
`<NorthernSTDev>/<LineSTDev>`
`<EasternSTDev>/<SampleSTDev>`
`<NorthernBias>/<LineBias>`
`<EasternBias>/<SampleBias>`

I'm not sure what you have in mind to incorporate these. Maybe the existing fields `card4l:northern_geometric_accuracy` and `card4l:eastern_geometric_accuracy` could be changed into objects so that stdev and bias are covered each:

```json
"card4l:northern_geometric_accuracy": {
      "stdev": 123,
      "bias": 456
    },
```

Also for the missing target requirement a new field such as `card4l:geometric_accuracy_radial_rmse` (or `card4l:radial_rmse_geometric_accuracy`?) could be added.

_Originally posted by @maawoo in https://github.com/stac-extensions/card4l/issues/8#issuecomment-1007287200_

**Comment by m-mohr** [comment]
Just a note for now: These fields (`card4l:northern_geometric_accuracy` and `card4l:eastern_geometric_accuracy`) are actually shared with the EO CARD4L part, so we need to be careful with changing them.

**Comment by m-mohr** [comment]
@maawoo In the XLSX it says "* (4.3) depending on whether <GeoCorrAccuracy>  type is "GTC" or "SlantRange" projection". Do you know what that means? Which requirements apply for each of them individually?

**Comment by maawoo** [comment]
> @maawoo In the XLSX it says "* (4.3) depending on whether type is "GTC" or "SlantRange" projection". Do you know what that means? Which requirements apply for each of them individually?

Slant Range: 
The natural radar range observation coordinate, defined as the line-of-sight from the radar to each reflecting object. [1]
Sentinel-1 SLC scenes are, for example, provided in slant range.

GTC = Geocoded Terrain Corrected = Ground range: 
Ground range coordinates are the slant range coordinates projected onto the ellipsoid of the Earth. [1]
Sentinel-1 GRD is a data product in ground range. 

[1] https://sentinel.esa.int/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-1

---

As far as I understand, the CARD4L specification requires the proper terminology depending on the type, i.e.: `NorthernSTDev` AND `EasternSTDev` in case of GTC. `LineSTDev` and `SampleSTDev` in case of Slant Range.

**Comment by m-mohr** [comment]
We need to split optical and sar definitions here.

**Comment by m-mohr** [comment]
Also applied the changes to Optical.
