### ISSUE TITLE
Clarify open SAR questions with CEOS

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/card4l#12]
- 1.7.9: The CARD4L specification is not clear whether a string representation of a CRS is required or whether an EPSG code would fulfill the requirement already.
- 4.4: In the CARD4L metadata specification the Gridding Convention details seem to be required although not required in the textual specification.

**Comment by maawoo** [comment]
- 1.6.5: Does an [Item Link](https://github.com/stac-extensions/card4l/tree/main/sar#stac-item-links) pointing to an orbit data file satisfy the target requirement? The CARD4L metadata specification seems to require state vector objects in the metadata file. If that's actually the case, how can/should at least five state vectors be chosen? Is it okay to select the first few or should they be selected randomly?

**Comment by maawoo** [comment]
- 1.6.5: StateVector information in the product instead of source metadata?

**Comment by m-mohr** [comment]
General: CEOS is aware of ambiguity and wants to change it. Probably originates from different names in different missions.
1.7.9: EPSG + (WKT2 or PROJJSON)
4.4: CEOS wants to clarify.  A free text description is required, with an optional URL or DOI.
1.6.5: ...
2.5: ...
