### ISSUE TITLE
Azimuth- and Range resolution 1.6.7

### ISSUE THREAD

**Issue by maawoo** [stac-extensions/card4l#14]
Both are required per beam since v5.5.5 of the CARD4L metadata specification (section 1.6.7), which is currently not possible using `sar:resolution_azimuth` and `sar:resolution_range`. 
[Here](https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-1-sar/products-algorithms/level-1/single-look-complex/interferometric-wide-swath) is an example of resolution per beam for Sentinel-1 SLC data and [here](https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-1-sar/products-algorithms/level-1-algorithms/ground-range-detected/iw) for GRD data.

**Comment by m-mohr** [comment]
CEOS needs to check internally, a potential solution could be to move the <Beam> tags to target.
In the PDF files there's no mention about "per beam". What are the single values then? A mean?

**Comment by maawoo** [comment]
Hi @m-mohr, 
I just realized that we're using `sar:resolution_azimuth` and `sar:resolution_range` now in a different way (mean) than intended by the extension ("maximum ability to distinguish two adjacent targets parallel to the flight path"). I think we should change this again before release. Sorry for not noticing earlier!

**Comment by m-mohr** [comment]
Thanks for spotting this!
